<?xml version='1.0' encoding='UTF-8'?>
<definitions 
xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" 
xmlns:wsp="http://www.w3.org/ns/ws-policy" 
xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" 
xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
xmlns:tns="http://ws/" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns="http://schemas.xmlsoap.org/wsdl/" 
targetNamespace="http://ws/" 
name="PoistenieFromWSDL">

    <types>
        <xsd:schema> <!-- schemaLocation="http://localhost:8080/mavenproject1/PoistenieFromWSDL?xsd=1" -->
            <xsd:import namespace="http://ws/" schemaLocation="file:/home/petra/Documents/I-ASOS/01_Prednasky/P06-26_10/PoistenieFromWSDL.xsd"/> 
        </xsd:schema>
    </types>

    <message name="hladaj">
        <part name="parameters" element="tns:hladaj"/>
    </message>
    <message name="hladajResponse">
        <part name="parameters" element="tns:hladajResponse"/>
    </message>

    <portType name="PoistenieFromWSDL">

        <operation name="hladaj">
            <input wsam:Action="http://ws/PoistenieFromWSDL/hladajRequest" message="tns:hladaj"/>
            <output wsam:Action="http://ws/PoistenieFromWSDL/hladajResponse" message="tns:hladajResponse"/>
        </operation>

    </portType>

    <binding name="PoistenieFromWSDLPortBinding" type="tns:PoistenieFromWSDL">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
        <operation name="hladaj">
            <soap:operation soapAction=""/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
        </operation>
    </binding>
    <service name="PoistenieFromWSDL">
        <port name="PoistenieFromWSDLPort" binding="tns:PoistenieFromWSDLPortBinding">
            <soap:address location="http://localhost:8080/02_ContractFirstServer/PoistenieFromWSDL"/>
        </port>
    </service>
</definitions>